version: "3"
services:
  expressjs-dev:
    image: ghcr.io/cookify-webapp/cookify-backend:dev
    restart: unless-stopped
    container_name: "expressjs-dev"
    env_file:
      - ./.env.development
    ports:
      - "5001:5001"
    volumes:
      - "/home/cookifywebapp/cookify-devops/seed-image:/app-dist/seed-image"
networks:
  default:
    external:
      name: cookify-devops_cookify-webapp
