version: "3"
services:
  expressjs-prd:
    image: ghcr.io/cookify-webapp/cookify-backend:prd
    restart: unless-stopped
    container_name: "expressjs"
    env_file:
      - ./cookify-backend/.env
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
networks:
  default:
    external:
      name: cookify-devops_cookify-webapp-prd