export enum errorText {
  CORS = 'Not allowed by CORS',
  SECRET = 'Missing token secret in environment',
  TOKEN = 'Invalid token',
  AUTH_HEADER = 'Multiple authentication headers detected',
  USERNAME = 'Incorrect username',
  PASSWORD = 'Incorrect password',
  ACCOUNT_NOT_FOUND = 'Account not found',
  AUTH = 'Please authenticate',
  ADMIN = 'This account is unauthorized as admin',
  DATA = 'Invalid data',
  ID = 'No documents found, please check the id',
  PARAM = 'Invalid path parameter(s)',
  QUERY = 'Invalid request query(s)',
  DELETE = 'No documents were deleted, please check the request parameter(s)',
  IMG_EXT = 'Invalid image extension, only images are allowed',
}
